type = "<class '__main__.Simple'>"

[body.fields]
a = 5
b = 787
x = [ 9, 8, 7, 6, 5, 4, 21,]

[body.class]
type = "class"

[body.fields.square]
type = "function"

[body.fields.InsideClass]
type = "class"

[body.fields.hate]
type = "function"

[body.class.body]
classname = "Simple"
metaclasses = "(<class 'object'>,)"

[body.fields.square.body]
modulename = "__main__"
functionname = "<lambda>"

[body.fields.InsideClass.body]
classname = "InsideClass"
metaclasses = "(<class 'object'>,)"

[body.fields.hate.body]
modulename = "__main__"
functionname = "hate"

[body.class.body.attributedict]
a = 5
b = 787
x = [ 9, 8, 7, 6, 5, 4, 21,]

[body.fields.square.body.globals]

[body.fields.square.body.CodeType]
co_argcount = 2
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_nlocals = 2
co_stacksize = 2
co_flags = 67
co_code = [ 124, 1, 100, 1, 19, 0, 83, 0,]
co_consts = [ "None", 2,]
co_names = []
co_varnames = [ "slf", "x",]
co_filename = "D:\\ispl2\\laba2_temp\\cleartest.py"
co_name = "<lambda>"
co_firstlineno = 14
co_lnotab = []
co_freevars = []
co_cellvars = []

[body.fields.InsideClass.body.attributedict]
insidevalue = "inside value"

[body.fields.hate.body.globals]
global_hate = "i hate class method's  serialization :)))"

[body.fields.hate.body.CodeType]
co_argcount = 1
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_nlocals = 1
co_stacksize = 2
co_flags = 67
co_code = [ 116, 0, 116, 1, 131, 1, 1, 0, 100, 0, 83, 0,]
co_consts = [ "None",]
co_names = [ "print", "global_hate",]
co_varnames = [ "self",]
co_filename = "D:\\ispl2\\laba2_temp\\cleartest.py"
co_name = "hate"
co_firstlineno = 19
co_lnotab = [ 0, 1,]
co_freevars = []
co_cellvars = []

[body.class.body.attributedict.square]
type = "function"

[body.class.body.attributedict.InsideClass]
type = "class"

[body.class.body.attributedict.hate]
type = "function"

[body.class.body.attributedict.square.body]
modulename = "__main__"
functionname = "<lambda>"

[body.class.body.attributedict.InsideClass.body]
classname = "InsideClass"
metaclasses = "(<class 'object'>,)"

[body.class.body.attributedict.hate.body]
modulename = "__main__"
functionname = "hate"

[body.class.body.attributedict.square.body.globals]

[body.class.body.attributedict.square.body.CodeType]
co_argcount = 2
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_nlocals = 2
co_stacksize = 2
co_flags = 67
co_code = [ 124, 1, 100, 1, 19, 0, 83, 0,]
co_consts = [ "None", 2,]
co_names = []
co_varnames = [ "slf", "x",]
co_filename = "D:\\ispl2\\laba2_temp\\cleartest.py"
co_name = "<lambda>"
co_firstlineno = 14
co_lnotab = []
co_freevars = []
co_cellvars = []

[body.class.body.attributedict.InsideClass.body.attributedict]
insidevalue = "inside value"

[body.class.body.attributedict.hate.body.globals]
global_hate = "i hate class method's  serialization :)))"

[body.class.body.attributedict.hate.body.CodeType]
co_argcount = 1
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_nlocals = 1
co_stacksize = 2
co_flags = 67
co_code = [ 116, 0, 116, 1, 131, 1, 1, 0, 100, 0, 83, 0,]
co_consts = [ "None",]
co_names = [ "print", "global_hate",]
co_varnames = [ "self",]
co_filename = "D:\\ispl2\\laba2_temp\\cleartest.py"
co_name = "hate"
co_firstlineno = 19
co_lnotab = [ 0, 1,]
co_freevars = []
co_cellvars = []
